import { type Item, ItemCategory } from "../backend.d";

const NOW = BigInt(Date.now()) * BigInt(1_000_000);

export const GIFT_ITEMS_SEED: Item[] = [
  "Millet Chikkies",
  "Coated Almond",
  "Bliss Flavored Chocolates",
  "Sugar Free Dark 70% (Cocoa Diva)",
  "Sugar Free Dark 55% (Cocoa Diva)",
  "Sugar Free Milk 40% (Cocoa Diva)",
  "Sugarfree Dark Himalayan Pink Salt 70% (Cocoa Diva)",
  "Sugarfree Dark Hazelnuts 70% (Cocoa Diva)",
  "Sugarfree Dark Almonds 70% (Cocoa Diva)",
  "Wheat Chrispies Compound Chocolate (Cocoa Diva)",
  "Butterscotch Compound Chocolate (Cocoa Diva)",
  "Almond Compound Chocolate (Cocoa Diva)",
  "Energy Bar",
  "Plain Dark Thins (Chocolate Philosophy)",
  "Roasted Almond Thins (Chocolate Philosophy)",
  "Hazelnut Thins (Chocolate Philosophy)",
  "Sea Salt Thins (Chocolate Philosophy)",
  "Mint Thins (Chocolate Philosophy)",
  "Leather Folders",
  "Notepads",
  "Pens",
  "Pencils",
  "Jute Bags",
  "Silk Shawls",
  "Flower Bouquet",
].map((name, idx) => ({
  id: BigInt(idx + 1),
  name,
  category: ItemCategory.gift,
  stockQty: BigInt(0),
  createdAt: NOW,
}));

export const BEVERAGE_ITEMS_SEED: Item[] = [
  "Veen Water 330ml",
  "Regular Coke",
  "Diet Coke",
  "Red Bull",
  "Sprite",
  "Thumps Up",
  "Fanta",
  "Sparkling Water",
  "Arka Orange Juice",
  "Arka Valencia Orange Juice",
  "Arka Pomegranate Juice",
  "Arka Apple Juice",
  "Arka Sugarcane Juice",
  "Cranberry Oatmeal Cookies",
  "Almond Orange Cookies",
  "Kiru Kudo Millet Almond Snack",
  "Kiru Ragi Choco Cookies",
  "Kiru Plain Banana Millet Snack",
  "Kiru Ajwain Banana Millet",
  "Kiru Pearl Coconut Almond Snack",
  "Millet Crunchies Onion & Cream",
  "Millet Crunchies Tomato",
  "Millet Crunchies Masala",
  "Millet Cookies Butter & Nuts",
].map((name, idx) => ({
  id: BigInt(idx + 1),
  name,
  category: ItemCategory.beverage,
  stockQty: BigInt(0),
  createdAt: NOW,
}));
