/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ApprovedUserRecord {
  'status' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : string,
  'tempUserId' : string,
  'email' : string,
  'mobile' : string,
  'tempPassword' : string,
}
export interface BookingRequest {
  'id' : string,
  'startTime' : string,
  'status' : string,
  'contact' : string,
  'endTime' : string,
  'date' : string,
  'designation' : string,
  'createdAt' : Time,
  'room' : string,
  'bookingPurpose' : string,
  'submittedBy' : string,
  'organizerName' : string,
  'notes' : string,
  'bookingType' : string,
  'eventName' : string,
}
export interface Item {
  'id' : bigint,
  'stockQty' : bigint,
  'name' : string,
  'createdAt' : Time,
  'category' : ItemCategory,
}
export type ItemCategory = { 'gift' : null } |
  { 'beverage' : null };
export interface Notification {
  'id' : string,
  'title' : string,
  'recipientKey' : string,
  'notificationType' : string,
  'createdAt' : Time,
  'credentialsUserId' : string,
  'isRead' : boolean,
  'credentialsPassword' : string,
  'message' : string,
}
export interface RegRequest {
  'id' : string,
  'status' : RegStatus,
  'name' : string,
  'role' : string,
  'tempUserId' : string,
  'submittedAt' : Time,
  'email' : string,
  'mobile' : string,
  'tempPassword' : string,
}
export type RegStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Room {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
}
export interface StockApprovalRequest {
  'id' : string,
  'status' : string,
  'role' : string,
  'submittedAt' : Time,
  'description' : string,
  'dataType' : string,
  'requestedByName' : string,
}
export interface StockEntry {
  'id' : bigint,
  'itemId' : bigint,
  'staffName' : string,
  'availableQty' : bigint,
  'date' : Time,
  'createdAt' : Time,
  'createdBy' : Principal,
  'closingQty' : bigint,
  'balanceQty' : bigint,
  'roomId' : bigint,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItem' : ActorMethod<[string, ItemCategory, bigint], bigint>,
  'addRoom' : ActorMethod<[string, string], bigint>,
  'approveBookingRequest' : ActorMethod<[string], undefined>,
  'approveRegistration' : ActorMethod<[string, string, string], undefined>,
  'approveStockApprovalRequest' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStockEntry' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, string, Time],
    bigint
  >,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'deleteRoom' : ActorMethod<[bigint], undefined>,
  'deleteStockEntry' : ActorMethod<[bigint], undefined>,
  'getAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'getAllEntries' : ActorMethod<[], Array<StockEntry>>,
  'getAllRegistrationRequests' : ActorMethod<[], Array<RegRequest>>,
  'getAllStockApprovalRequests' : ActorMethod<[], Array<StockApprovalRequest>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    { 'roomsCount' : bigint, 'itemsCount' : bigint }
  >,
  'getEntriesByCategory' : ActorMethod<[ItemCategory], Array<StockEntry>>,
  'getItemsByCategory' : ActorMethod<[ItemCategory], Array<Item>>,
  'getMyEntries' : ActorMethod<[], Array<StockEntry>>,
  'getNotificationsForRecipient' : ActorMethod<[string], Array<Notification>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listRooms' : ActorMethod<[], Array<Room>>,
  'loginWithCredentials' : ActorMethod<
    [string, string],
    [] | [ApprovedUserRecord]
  >,
  'markAllNotificationsReadForRecipient' : ActorMethod<[string], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'prefilledItems' : ActorMethod<[Array<Item>, Array<Item>], undefined>,
  'rejectBookingRequest' : ActorMethod<[string], undefined>,
  'rejectRegistration' : ActorMethod<[string], undefined>,
  'rejectStockApprovalRequest' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'storeNotification' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'submitBookingRequest' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'submitRegistration' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitStockApprovalRequest' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateItem' : ActorMethod<[bigint, string, ItemCategory, bigint], undefined>,
  'updateRoom' : ActorMethod<[bigint, string, string], undefined>,
  'updateStockEntry' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, string, Time],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];