/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemCategory = IDL.Variant({
  'gift' : IDL.Null,
  'beverage' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const StockEntry = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'staffName' : IDL.Text,
  'availableQty' : IDL.Nat,
  'date' : Time,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'closingQty' : IDL.Nat,
  'balanceQty' : IDL.Nat,
  'roomId' : IDL.Nat,
});
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'category' : ItemCategory,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItem' : IDL.Func([IDL.Text, ItemCategory, IDL.Nat], [IDL.Nat], []),
  'addRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStockEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, Time],
      [IDL.Nat],
      [],
    ),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'deleteRoom' : IDL.Func([IDL.Nat], [], []),
  'deleteStockEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(StockEntry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [IDL.Record({ 'roomsCount' : IDL.Nat, 'itemsCount' : IDL.Nat })],
      ['query'],
    ),
  'getEntriesByCategory' : IDL.Func(
      [ItemCategory],
      [IDL.Vec(StockEntry)],
      ['query'],
    ),
  'getItemsByCategory' : IDL.Func([ItemCategory], [IDL.Vec(Item)], ['query']),
  'getMyEntries' : IDL.Func([], [IDL.Vec(StockEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'prefilledItems' : IDL.Func([IDL.Vec(Item), IDL.Vec(Item)], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateItem' : IDL.Func([IDL.Nat, IDL.Text, ItemCategory, IDL.Nat], [], []),
  'updateRoom' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateStockEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, Time],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemCategory = IDL.Variant({
    'gift' : IDL.Null,
    'beverage' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const StockEntry = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'staffName' : IDL.Text,
    'availableQty' : IDL.Nat,
    'date' : Time,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'closingQty' : IDL.Nat,
    'balanceQty' : IDL.Nat,
    'roomId' : IDL.Nat,
  });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'category' : ItemCategory,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItem' : IDL.Func([IDL.Text, ItemCategory, IDL.Nat], [IDL.Nat], []),
    'addRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStockEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, Time],
        [IDL.Nat],
        [],
      ),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'deleteRoom' : IDL.Func([IDL.Nat], [], []),
    'deleteStockEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(StockEntry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [IDL.Record({ 'roomsCount' : IDL.Nat, 'itemsCount' : IDL.Nat })],
        ['query'],
      ),
    'getEntriesByCategory' : IDL.Func(
        [ItemCategory],
        [IDL.Vec(StockEntry)],
        ['query'],
      ),
    'getItemsByCategory' : IDL.Func([ItemCategory], [IDL.Vec(Item)], ['query']),
    'getMyEntries' : IDL.Func([], [IDL.Vec(StockEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'prefilledItems' : IDL.Func([IDL.Vec(Item), IDL.Vec(Item)], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateItem' : IDL.Func([IDL.Nat, IDL.Text, ItemCategory, IDL.Nat], [], []),
    'updateRoom' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateStockEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, Time],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };