/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StockEntry {
    id: bigint;
    itemId: bigint;
    staffName: string;
    availableQty: bigint;
    date: Time;
    createdAt: Time;
    createdBy: Principal;
    closingQty: bigint;
    balanceQty: bigint;
    roomId: bigint;
}
export type Time = bigint;
export interface BookingRequest {
    id: string;
    startTime: string;
    status: string;
    contact: string;
    endTime: string;
    date: string;
    designation: string;
    createdAt: Time;
    room: string;
    bookingPurpose: string;
    submittedBy: string;
    organizerName: string;
    notes: string;
    bookingType: string;
    eventName: string;
}
export interface Room {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface StockApprovalRequest {
    id: string;
    status: string;
    role: string;
    submittedAt: Time;
    description: string;
    dataType: string;
    requestedByName: string;
}
export interface Item {
    id: bigint;
    stockQty: bigint;
    name: string;
    createdAt: Time;
    category: ItemCategory;
}
export interface RegRequest {
    id: string;
    status: RegStatus;
    name: string;
    role: string;
    tempUserId: string;
    submittedAt: Time;
    email: string;
    mobile: string;
    tempPassword: string;
}
export interface Notification {
    id: string;
    title: string;
    recipientKey: string;
    notificationType: string;
    createdAt: Time;
    credentialsUserId: string;
    isRead: boolean;
    credentialsPassword: string;
    message: string;
}
export interface ApprovedUserRecord {
    status: string;
    name: string;
    createdAt: Time;
    role: string;
    tempUserId: string;
    email: string;
    mobile: string;
    tempPassword: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ItemCategory {
    gift = "gift",
    beverage = "beverage"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addItem(name: string, category: ItemCategory, stockQty: bigint): Promise<bigint>;
    addRoom(name: string, description: string): Promise<bigint>;
    approveBookingRequest(id: string): Promise<void>;
    approveRegistration(id: string, tempUserId: string, tempPassword: string): Promise<void>;
    approveStockApprovalRequest(id: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createStockEntry(roomId: bigint, itemId: bigint, availableQty: bigint, closingQty: bigint, balanceQty: bigint, staffName: string, date: Time): Promise<bigint>;
    deleteItem(id: bigint): Promise<void>;
    deleteRoom(id: bigint): Promise<void>;
    deleteStockEntry(id: bigint): Promise<void>;
    getAllBookingRequests(): Promise<Array<BookingRequest>>;
    getAllEntries(): Promise<Array<StockEntry>>;
    getAllRegistrationRequests(): Promise<Array<RegRequest>>;
    getAllStockApprovalRequests(): Promise<Array<StockApprovalRequest>>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        roomsCount: bigint;
        itemsCount: bigint;
    }>;
    getEntriesByCategory(category: ItemCategory): Promise<Array<StockEntry>>;
    getItemsByCategory(category: ItemCategory): Promise<Array<Item>>;
    getMyEntries(): Promise<Array<StockEntry>>;
    getNotificationsForRecipient(recipientKey: string): Promise<Array<Notification>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listRooms(): Promise<Array<Room>>;
    loginWithCredentials(userId: string, password: string): Promise<ApprovedUserRecord | null>;
    markAllNotificationsReadForRecipient(recipientKey: string): Promise<void>;
    markNotificationRead(id: string): Promise<void>;
    prefilledItems(gifts: Array<Item>, beverages: Array<Item>): Promise<void>;
    rejectBookingRequest(id: string): Promise<void>;
    rejectRegistration(id: string): Promise<void>;
    rejectStockApprovalRequest(id: string): Promise<void>;
    requestApproval(): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    storeNotification(recipientKey: string, notificationType: string, title: string, message: string, credentialsUserId: string, credentialsPassword: string): Promise<string>;
    submitBookingRequest(id: string, bookingType: string, room: string, date: string, startTime: string, endTime: string, eventName: string, organizerName: string, contact: string, notes: string, submittedBy: string, designation: string, bookingPurpose: string): Promise<void>;
    submitRegistration(id: string, name: string, email: string, mobile: string, role: string): Promise<void>;
    submitStockApprovalRequest(id: string, requestedByName: string, role: string, dataType: string, description: string): Promise<void>;
    updateItem(id: bigint, name: string, category: ItemCategory, stockQty: bigint): Promise<void>;
    updateRoom(id: bigint, name: string, description: string): Promise<void>;
    updateStockEntry(id: bigint, roomId: bigint, itemId: bigint, availableQty: bigint, closingQty: bigint, balanceQty: bigint, staffName: string, date: Time): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, ApprovedUserRecord as _ApprovedUserRecord, Item as _Item, ItemCategory as _ItemCategory, RegRequest as _RegRequest, RegStatus as _RegStatus, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addItem(arg0: string, arg1: ItemCategory, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0, to_candid_ItemCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0, to_candid_ItemCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addRoom(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoom(arg0, arg1);
            return result;
        }
    }
    async approveBookingRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBookingRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBookingRequest(arg0);
            return result;
        }
    }
    async approveRegistration(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRegistration(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRegistration(arg0, arg1, arg2);
            return result;
        }
    }
    async approveStockApprovalRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveStockApprovalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveStockApprovalRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createStockEntry(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string, arg6: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStockEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStockEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async deleteRoom(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoom(arg0);
            return result;
        }
    }
    async deleteStockEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStockEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStockEntry(arg0);
            return result;
        }
    }
    async getAllBookingRequests(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingRequests();
            return result;
        }
    }
    async getAllEntries(): Promise<Array<StockEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntries();
            return result;
        }
    }
    async getAllRegistrationRequests(): Promise<Array<RegRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistrationRequests();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistrationRequests();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStockApprovalRequests(): Promise<Array<StockApprovalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStockApprovalRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStockApprovalRequests();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        roomsCount: bigint;
        itemsCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getEntriesByCategory(arg0: ItemCategory): Promise<Array<StockEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByCategory(to_candid_ItemCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByCategory(to_candid_ItemCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getItemsByCategory(arg0: ItemCategory): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByCategory(to_candid_ItemCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByCategory(to_candid_ItemCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEntries(): Promise<Array<StockEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEntries();
            return result;
        }
    }
    async getNotificationsForRecipient(arg0: string): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsForRecipient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsForRecipient(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRooms();
            return result;
        }
    }
    async loginWithCredentials(arg0: string, arg1: string): Promise<ApprovedUserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithCredentials(arg0, arg1);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithCredentials(arg0, arg1);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsReadForRecipient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsReadForRecipient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsReadForRecipient(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async prefilledItems(arg0: Array<Item>, arg1: Array<Item>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.prefilledItems(to_candid_vec_n22(this._uploadFile, this._downloadFile, arg0), to_candid_vec_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.prefilledItems(to_candid_vec_n22(this._uploadFile, this._downloadFile, arg0), to_candid_vec_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async rejectBookingRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBookingRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBookingRequest(arg0);
            return result;
        }
    }
    async rejectRegistration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRegistration(arg0);
            return result;
        }
    }
    async rejectStockApprovalRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectStockApprovalRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectStockApprovalRequest(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async storeNotification(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.storeNotification(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeNotification(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitBookingRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
    async submitRegistration(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRegistration(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRegistration(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitStockApprovalRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitStockApprovalRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitStockApprovalRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateItem(arg0: bigint, arg1: string, arg2: ItemCategory, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, arg1, to_candid_ItemCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, arg1, to_candid_ItemCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateRoom(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoom(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoom(arg0, arg1, arg2);
            return result;
        }
    }
    async updateStockEntry(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string, arg7: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStockEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStockEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ItemCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemCategory): ItemCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_RegRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegRequest): RegRequest {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RegStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegStatus): RegStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApprovedUserRecord]): ApprovedUserRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockQty: bigint;
    name: string;
    createdAt: _Time;
    category: _ItemCategory;
}): {
    id: bigint;
    stockQty: bigint;
    name: string;
    createdAt: Time;
    category: ItemCategory;
} {
    return {
        id: value.id,
        stockQty: value.stockQty,
        name: value.name,
        createdAt: value.createdAt,
        category: from_candid_ItemCategory_n15(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n20(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _RegStatus;
    name: string;
    role: string;
    tempUserId: string;
    submittedAt: _Time;
    email: string;
    mobile: string;
    tempPassword: string;
}): {
    id: string;
    status: RegStatus;
    name: string;
    role: string;
    tempUserId: string;
    submittedAt: Time;
    email: string;
    mobile: string;
    tempPassword: string;
} {
    return {
        id: value.id,
        status: from_candid_RegStatus_n8(_uploadFile, _downloadFile, value.status),
        name: value.name,
        role: value.role,
        tempUserId: value.tempUserId,
        submittedAt: value.submittedAt,
        email: value.email,
        mobile: value.mobile,
        tempPassword: value.tempPassword
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gift: null;
} | {
    beverage: null;
}): ItemCategory {
    return "gift" in value ? ItemCategory.gift : "beverage" in value ? ItemCategory.beverage : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegRequest>): Array<RegRequest> {
    return value.map((x)=>from_candid_RegRequest_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_ItemCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemCategory): _ItemCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Item_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Item): _Item {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockQty: bigint;
    name: string;
    createdAt: Time;
    category: ItemCategory;
}): {
    id: bigint;
    stockQty: bigint;
    name: string;
    createdAt: _Time;
    category: _ItemCategory;
} {
    return {
        id: value.id,
        stockQty: value.stockQty,
        name: value.name,
        createdAt: value.createdAt,
        category: to_candid_ItemCategory_n1(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemCategory): {
    gift: null;
} | {
    beverage: null;
} {
    return value == ItemCategory.gift ? {
        gift: null
    } : value == ItemCategory.beverage ? {
        beverage: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Item>): Array<_Item> {
    return value.map((x)=>to_candid_Item_n23(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
